services:
  app:
    build: ./java-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/kafka
      DB_USER: root
      DB_PASSWORD: 123
      API_KEY: uWpqxW0T9ml1EbYb5J2LR0F9mMbVA6sk
      API_SECRET: i2qNwaXvjlmhTNTS
    depends_on:
      mysql:
        condition: service_healthy
    networks: # <--- ADD THIS LINE
      - backend

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: kafka
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    networks:
      - backend

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.0.1'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'
    networks:
      - backend

  kafka:
    image: 'confluentinc/cp-kafka:7.0.1'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # localhost instead of 'kafka' for local
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - backend
  node_consumer_1:
    build: ./node-order-consumer
    volumes:
      - ./node-order-consumer:/usr/src/app
    working_dir: /usr/src/app
    command: node consumer.js
    depends_on:
      - kafka
    networks:
      - backend
    restart: always

  node_consumer_2:
    build: ./node-order-consumer
    volumes:
      - ./node-order-consumer:/usr/src/app
    working_dir: /usr/src/app
    command: node consumer.js
    depends_on:
      - kafka
    networks:
      - backend
    restart: always

volumes:
  mysql_data:

networks:
  backend: